[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 10
startupDelay = 5
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 